version: '3'

services:
    redis:
      image: redis:latest
      container_name: redis_distributed_queue
      restart: always
      ports:
        - '6379:6379'
      command: redis-server --save 30 1 --loglevel warning --requirepass dummy-pass # dummy-pass is our password
      volumes:
        - data-volume:/data

volumes:
  data-volume: